# -*- coding: utf-8 -*-
"""499_MonteCarlo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rZBw2ShKvJCvXWddoukRK_X2kqIuEuaF
"""

# Monte Carlo Simulation:
import random
import math

numberOfHits = 0   # to count numberOfHits

# Using for loop to generate 1000000 points
for _ in range(1000000):

    # Using random.uniform to generate a random point (x, y) 
    random_x = random.uniform(-1, 1)
    random_y = random.uniform(-1, 1)
    
    # If point falls in the circle then increase numberOfHits by 1
    if math.sqrt(random_x * random_x + random_y * random_y) <= 1:
        numberOfHits += 1

# Calculating approximate value of pi using given formula
approximated_pi = 4 * numberOfHits / 1000000
print(f"Approximate value of pi is : {approximated_pi}")
